-- Migration: add_optimization_indexes
-- This migration creates all tables and indexes based on the Prisma schema.

-- CreateTable Level
CREATE TABLE "levels" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "levelNumber" INTEGER NOT NULL UNIQUE,
    "minPoints" INTEGER NOT NULL,
    "maxPoints" INTEGER,
    "name" TEXT,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- CreateTable User
CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "username" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL,
    "levelId" INTEGER NOT NULL DEFAULT 1,
    "totalPoints" INTEGER NOT NULL DEFAULT 0
);

-- CreateTable Post
CREATE TABLE "posts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "authorId" INTEGER NOT NULL,
    "approved" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- CreateTable Skill
CREATE TABLE "skills" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "description" TEXT,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- CreateTable PostSkill (join)
CREATE TABLE "post_skills" (
    "postId" INTEGER NOT NULL,
    "skillId" INTEGER NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("postId", "skillId")
);

-- CreateTable UserSkill (join with extra)
CREATE TABLE "user_skills" (
    "userId" INTEGER NOT NULL,
    "skillId" INTEGER NOT NULL,
    "sourcePostId" INTEGER,
    "claimedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("userId", "skillId")
);

-- CreateTable PointsLog
CREATE TABLE "points_log" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" INTEGER NOT NULL,
    "postId" INTEGER,
    "skillId" INTEGER,
    "points" INTEGER NOT NULL,
    "reason" TEXT NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- AddForeignKey User.levelId -> Level.id
ALTER TABLE "users" ADD CONSTRAINT "users_levelId_fkey" FOREIGN KEY ("levelId") REFERENCES "levels"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey Post.authorId -> User.id
ALTER TABLE "posts" ADD CONSTRAINT "posts_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey PostSkill.postId -> Post.id
ALTER TABLE "post_skills" ADD CONSTRAINT "post_skills_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey PostSkill.skillId -> Skill.id
ALTER TABLE "post_skills" ADD CONSTRAINT "post_skills_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey UserSkill.userId -> User.id
ALTER TABLE "user_skills" ADD CONSTRAINT "user_skills_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey UserSkill.skillId -> Skill.id
ALTER TABLE "user_skills" ADD CONSTRAINT "user_skills_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey UserSkill.sourcePostId -> Post.id (optional)
ALTER TABLE "user_skills" ADD CONSTRAINT "user_skills_sourcePostId_fkey" FOREIGN KEY ("sourcePostId") REFERENCES "posts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey PointsLog.userId -> User.id
ALTER TABLE "points_log" ADD CONSTRAINT "points_log_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey PointsLog.postId -> Post.id (optional)
ALTER TABLE "points_log" ADD CONSTRAINT "points_log_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey PointsLog.skillId -> Skill.id (optional)
ALTER TABLE "points_log" ADD CONSTRAINT "points_log_skillId_fkey" FOREIGN KEY ("skillId") REFERENCES "skills"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- CreateIndexes for foreign key optimization

CREATE INDEX "User_levelId_idx" ON "users"("levelId");
CREATE INDEX "Post_authorId_idx" ON "posts"("authorId");
CREATE INDEX "PostSkill_skillId_idx" ON "post_skills"("skillId");
CREATE INDEX "UserSkill_skillId_idx" ON "user_skills"("skillId");
CREATE INDEX "UserSkill_sourcePostId_idx" ON "user_skills"("sourcePostId");
CREATE INDEX "PointsLog_userId_idx" ON "points_log"("userId");
CREATE INDEX "PointsLog_postId_idx" ON "points_log"("postId");
CREATE INDEX "PointsLog_skillId_idx" ON "points_log"("skillId");
